name: ldv_app
publish_to: 'none'

version: 0.1.0+2

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^16.2.1
  intl: any
  retrofit: ^4.9.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  dio: ^5.9.1

dev_dependencies:
  retrofit_generator: ^10.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.10.5
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  injectable_generator: ^2.12.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_foreground_inset: 25
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
  ios: true
  web:
    generate: false
  macos:
    generate: false
